version: '3.3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/dockerApp
      - /dockerApp/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
