version: '3.3'
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
